USE [master]
GO

/****** Object:  Database [WmiTesteDevs]    Script Date: 07/11/2022 09:14:15 ******/
CREATE DATABASE [WmiTesteDevs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WmiTesteDevs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLLOCAL\MSSQL\DATA\WmiTesteDevs.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WmiTesteDevs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLLOCAL\MSSQL\DATA\WmiTesteDevs_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WmiTesteDevs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WmiTesteDevs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET ARITHABORT OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WmiTesteDevs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WmiTesteDevs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WmiTesteDevs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WmiTesteDevs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET RECOVERY FULL 
GO

ALTER DATABASE [WmiTesteDevs] SET  MULTI_USER 
GO

ALTER DATABASE [WmiTesteDevs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WmiTesteDevs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WmiTesteDevs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WmiTesteDevs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WmiTesteDevs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WmiTesteDevs] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WmiTesteDevs] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WmiTesteDevs] SET  READ_WRITE 
GO